name: "CI"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    defaults:
      run:
        working-directory: "terraform"

    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      TF_VAR_dns_credentials: ${{ secrets.TF_VAR_DNS_CREDENTIALS }}
      TF_VAR_ssh_keys: ${{ secrets.TF_VAR_SSH_KEYS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out plan

      - name: Terraform Apply
        run: terraform apply -auto-approve "plan"
